apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-auditing-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-auditing-operator
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - pods
      - secrets
      - namespaces
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create

  - apiGroups:
      - apps
    resourceNames:
      - kube-auditing-operator
    resources:
      - deployments/finalizers
    verbs:
      - update

  - apiGroups:
      - auditing.kubesphere.io
    resources:
      - webhooks
      - rules
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-auditing-operator
subjects:
  - kind: ServiceAccount
    name: kube-auditing-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: kube-auditing-operator
  apiGroup: rbac.authorization.k8s.io

