- name: KubeSphere | Getting openldap installation files
  copy:
    src: "{{ item }}"
    dest: "{{ kubesphere_dir }}/"
  loop:
    - "openldap-ha"


- name: KubeSphere | Creating manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kubesphere_dir }}/{{ item.file }}"
  with_items:
    - { name: custom-values-openldap, file: custom-values-openldap.yaml }


- name: KubeSphere | Checking old openldap status
  shell: >
    {{ bin_dir }}/kubectl get pod
    -n kubesphere-system
    -l app=openldap,tier=database,version=openldap-2.4 | wc -l
  register: old_openldap_exist

- name: KubeSphere | Shutdown ks-account
  shell: >
    {{ bin_dir }}/kubectl -n kubesphere-system scale deployment ks-account --replicas=0
  when:
    - old_openldap_exist.stdout != "0"

- name: KubeSphere | Deleting and backup old openldap svc
  shell: >
    {{ bin_dir }}/kubectl get svc -n kubesphere-system openldap -o yaml > {{ kubesphere_dir }}/openldap-svc-backup.yaml
    &&
    {{ bin_dir }}/kubectl delete svc -n kubesphere-system openldap
  when:
    - old_openldap_exist.stdout != "0"


- name: KubeSphere | Checking openldap
  shell: >
    {{ bin_dir }}/helm list -n kubesphere-system | grep "ks-openldap"
  register: openldap_check
  failed_when: false


- name: KubeSphere | Deploying openldap
  shell: >
    {{ bin_dir }}/helm upgrade --install ks-openldap
    {{ kubesphere_dir }}/openldap-ha
    -f {{ kubesphere_dir }}/custom-values-openldap.yaml
    --set fullnameOverride=openldap
    --namespace kubesphere-system
  when:
    - (openldap_check.stdout.find("deployed") == -1) or (openldap_check.stdout.find("1.0") == -1)

- import_tasks: openldap-migration.yaml
  when:
    - old_openldap_exist.stdout != "0"


- name: KubeSphere | Restarting ks-account
  shell: >
    {{ bin_dir }}/kubectl -n kubesphere-system scale deployment ks-account --replicas=1
  when:
    - old_openldap_exist.stdout != "0"


- name: KubeSphere | Importing openldap status
  shell: >
    {{ bin_dir }}/kubectl patch cc ks-installer
    --type merge
    -p '{"status": {"openldap": {"status": "enabled", "enabledTime": "{{ lookup('pipe','date  +%Y-%m-%dT%H:%M:%S%Z') }}"}}}'
    -n kubesphere-system
  register: cc_result
  failed_when: "cc_result.stderr and 'Warning' not in cc_result.stderr"
  until: cc_result is succeeded
  retries: 5
  delay: 3