---

- hosts: localhost
  gather_facts: false
  roles:
    - kubesphere-defaults
    - role: kubeedge
      when:
        - "kubeedge is defined and kubeedge.enabled == true"
        - "status.kubeedge is not defined or status.kubeedge.status is not defined or status.kubeedge.status != 'enabled'"