---

- hosts: localhost
  gather_facts: false
  roles:
    - kubesphere-defaults
    - role: ks-multicluster
      when:
        - "multicluster is defined and multicluster.clusterRole == 'host'"
        - "status.multicluster is not defined or status.multicluster.status is not defined or status.multicluster.status != 'enabled'"
