---

- hosts: localhost
  gather_facts: false
  roles:
    - kubesphere-defaults
    - role: ks-istio
      when:
        - "status.servicemesh is not defined or status.servicemesh.status is not defined or status.servicemesh.status != 'enabled'"