---
- name: Monitoring | Installing etcd monitoring
  shell: "{{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/prometheus/{{ item }}"
  loop:
    - "etcd"
  register: etcd_result
  failed_when: "etcd_result.stderr and 'Warning' not in etcd_result.stderr and 'spec.clusterIP' not in etcd_result.stderr"
  until: etcd_result is succeeded
  retries: 5
  delay: 3
  when:
    - etcd.monitoring is defined
    - etcd.monitoring == true