FROM cr.loongnix.cn/distroless/static:latest

LABEL maintainer="wangweijie@loongson.cn"
LABEL description="Snapshot Controller"

COPY ./snapshot-controller snapshot-controller

ENTRYPOINT ["/snapshot-controller"]
