# map category name to icon
categoryIcon:
  "Database & Cache": "database"
  "Prometheus Exporter": "export"
  "Networking": "router"
  "Storage": "storage"
  "Image Registry": "cdn"
  "Big Data": "increase"
  "Message Queueing": "blockchain"
  "Web Server": "ip"
appNameReplace:
  "elasticsearch-exporter": "Elasticsearch Exporter"
  "harbor": "Harbor"
  "memcached": "Memcached"
  "minio": "MinIO"
  "mysql": "MySQL"
  "mysql-exporter": "MySQL Exporter"
  "nginx": "NGINX"
  "redis-exporter": "Redis Exporter"
  "tomcat": "Tomcat"
  "apisix": "APISIX"
  "etcd": "etcd"
  "mongodb": "MongoDB"
  "postgresql": "PostgreSQL"
  "rabbitmq": "RabbitMQ"
  "redis": "Redis"
  "radondb-mysql": "RadonDB MySQL"
