
apiVersion: v1
data:
  local_config.yaml: |
    server:
      http:
        hostname: localhost
        port: 8000
        static:
          production:
            /public: server/public
            /assets: dist/assets
            /dist: dist
      redis:
        port: 6379
        host: redis.kubesphere-system.svc
      redisTimeout: 5000
      sessionTimeout: 7200000
    client:
      version:
        kubesphere: {{ .Chart.AppVersion }}
        kubernetes: {{ .Values.kube_version }}
        openpitrix: {{ .Chart.AppVersion }}
      enableKubeConfig: true
    defaultClusterName: {{ .Values.console.defaultClusterName }}
kind: ConfigMap
metadata:
  name: ks-console-config
