apiVersion: v1
kind: ConfigMap
metadata:
  name: ks-router-config
data:
  ingress-controller-svc.yaml: |+
{{- include "ingress-controller-svc.yaml" . }}
  ingress-controller.yaml: |
{{- include "ingress-controller.yaml" . }}