

- name: servicemesh | upgrade-pre | disable old sidecar injection 
  shell: >
    {{ bin_dir }}/kubectl patch mutatingwebhookconfigurations istio-sidecar-injector-1-6-10 --type='json' -p='[{ "op": "replace", "path": "/webhooks/0/namespaceSelector/matchExpressions/3","value":{"key": "istio.io/rev", "operator": "In","values": ["1-6-10"]} }]'
  ignore_errors: true

- name: servicemesh | delete old validating webhook
  shell: >
    {{ bin_dir }}/kubectl delete validatingwebhookconfigurations istiod-istio-system
  ignore_errors: true