#!/usr/bin/env bash

set -eExo pipefail

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

TARGETPLATFORM="$1"
DOCKER_MACHINE_VERSION="$2"
#
INSTALL_ROOT=${DNF_INSTALL_ROOT-}
TARGET_BIN_PATH="${INSTALL_ROOT}/usr/bin"
export PATH="${TARGET_BIN_PATH}:${PATH}"
#
#case "${TARGETPLATFORM}" in
#    "linux/arm64")
#        ARCH=arm64
#        DOCKER_MACHINE_ARCH=aarch64
#        ;;
#    "linux/amd64" | "")
#        ARCH=amd64
#        DOCKER_MACHINE_ARCH=x86_64
#        ;;
#    "linux/s390x")
#        ARCH=s390x
#        DOCKER_MACHINE_ARCH=s390x
#        ;;
#    "linux/ppc64le")
#        ARCH=ppc64le
#        DOCKER_MACHINE_ARCH=ppc64le
#        ;;
#    "linux/riscv64")
#        ARCH=riscv64
#        DOCKER_MACHINE_ARCH=riscv64
#        ;;
#    *)
#        echo "Unexpected TARGETPLATFORM value: ${TARGETPLATFORM}"
#        ;;
#esac;
#
mkdir -p /etc/gitlab-runner/certs
chmod -R 700 /etc/gitlab-runner
#
#if grep 'docker-machine' "${SCRIPTPATH}/checksums-${ARCH}"; then
#  curl -L --fail "https://gitlab-docker-machine-downloads.s3.amazonaws.com/${DOCKER_MACHINE_VERSION}/docker-machine-Linux-${DOCKER_MACHINE_ARCH}" -o /tmp/docker-machine
#else
#  echo "No checksum specified for docker-machine, skipping."
#fi
#
#if [ -f "${SCRIPTPATH}/checksums-${ARCH}" ]; then
#  sha256sum -c -w "${SCRIPTPATH}/checksums-${ARCH}"
#fi

#if [ -f "/tmp/docker-machine" ]; then
#  install -m 555 -o 0 -g 0 /tmp/docker-machine "${TARGET_BIN_PATH}"/docker-machine
#  docker-machine --version
#fi
curl -L --fail "https://cloud.loongnix.cn/releases/loongarch64abi1/docker-machine/docker-machine/${DOCKER_MACHINE_VERSION}/docker-machine" -o /tmp/docker-machine
install -m 555 -o 0 -g 0 /tmp/docker-machine "${TARGET_BIN_PATH}"/docker-machine
if [ -f "/tmp/docker-machine" ]; then
  install -m 555 -o 0 -g 0 /tmp/docker-machine "${TARGET_BIN_PATH}"/docker-machine
  docker-machine --version
fi
