From scratch
MAINTAINER zhangwenlong@loongson.cn
ADD AnolisOS-8.10.rootfs.loongarch64.tar.gz / 
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' > /etc/timezone
CMD ["/bin/bash"]
