---

- hosts: localhost
  gather_facts: false
  roles:
    - kubesphere-defaults
    - role: ks-auditing
      when:
        - "status.auditing is not defined or status.auditing.status is not defined or status.auditing.status != 'enabled'"

