- name: ks-events | Creates directory
  file:
    path: "{{ kubesphere_dir }}/fluentbit-operator"
    state: directory

- name: ks-events | Creating manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kubesphere_dir }}/fluentbit-operator/{{ item.file }}"
  with_items:
    - { name: custom-output-elasticsearch-events, file: custom-output-elasticsearch-events.yaml }
    - { name: custom-input-events, file: custom-input-events.yaml }
    - { name: custom-filter-events, file: custom-filter-events.yaml }


- name: ks-events | Apply fluentbit operator custom resources
  shell: >
    {{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/fluentbit-operator