apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubesphere-prometheus-adapter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubesphere-prometheus-adapter
subjects:
- kind: ServiceAccount
  name: prometheus-adapter
  namespace: kubesphere-monitoring-system
