apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubesphere-custom-metrics-server-resources
rules:
- apiGroups:
  - custom.metrics.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
