apiVersion: v1
kind: Endpoints
metadata:
  labels:
    k8s-app: etcd
  name: etcd
  namespace: kube-system
subsets:
- addresses:
  - ip: 127.0.0.1
  ports:
  - name: metrics
    port: 2379
    protocol: TCP
